// === Unit Definitions (10 types) ===

import type { UnitDef } from './types.ts';

export const UNIT_DEFS: Record<string, UnitDef> = {
  militia: {
    id: 'militia',
    name: 'Militia',
    attack: 3,
    defense: 2,
    hp: 30,
    speed: 2,
    range: 1,
    trainCost: { food: 10, wood: 5 },
    trainTicks: 3,
    upkeepPerTick: { food: 0.5 },
    requires: {},
    tags: ['melee'],
  },
  warrior: {
    id: 'warrior',
    name: 'Warrior',
    attack: 6,
    defense: 4,
    hp: 50,
    speed: 2,
    range: 1,
    trainCost: { food: 15, iron: 5 },
    trainTicks: 5,
    upkeepPerTick: { food: 1, gold: 0.5 },
    requires: { building: 'barracks', tech: 'bronze_working' },
    tags: ['melee'],
  },
  archer: {
    id: 'archer',
    name: 'Archer',
    attack: 5,
    defense: 2,
    hp: 35,
    speed: 2,
    range: 3,
    trainCost: { food: 12, wood: 10 },
    trainTicks: 5,
    upkeepPerTick: { food: 0.8, gold: 0.3 },
    requires: { building: 'archery_range', tech: 'archery' },
    tags: ['ranged'],
  },
  spearman: {
    id: 'spearman',
    name: 'Spearman',
    attack: 4,
    defense: 7,
    hp: 45,
    speed: 2,
    range: 1,
    trainCost: { food: 12, wood: 8 },
    trainTicks: 4,
    upkeepPerTick: { food: 0.8, gold: 0.3 },
    requires: { building: 'barracks', tech: 'bronze_working' },
    tags: ['melee', 'anti_cavalry'],
  },
  cavalry: {
    id: 'cavalry',
    name: 'Cavalry',
    attack: 8,
    defense: 3,
    hp: 45,
    speed: 4,
    range: 1,
    trainCost: { food: 20, iron: 5, gold: 5 },
    trainTicks: 7,
    upkeepPerTick: { food: 1.5, gold: 1 },
    requires: { building: 'stable', tech: 'horseback_riding' },
    tags: ['cavalry', 'melee'],
  },
  siege_ram: {
    id: 'siege_ram',
    name: 'Siege Ram',
    attack: 15,
    defense: 1,
    hp: 60,
    speed: 1,
    range: 1,
    trainCost: { wood: 30, iron: 10 },
    trainTicks: 10,
    upkeepPerTick: { food: 1, gold: 1 },
    requires: { building: 'siege_workshop', tech: 'siege_warfare' },
    tags: ['siege'],
  },
  catapult: {
    id: 'catapult',
    name: 'Catapult',
    attack: 12,
    defense: 1,
    hp: 40,
    speed: 1,
    range: 5,
    trainCost: { wood: 25, iron: 15, gold: 5 },
    trainTicks: 12,
    upkeepPerTick: { food: 1, gold: 1.5 },
    requires: { building: 'siege_workshop', tech: 'siege_warfare' },
    tags: ['siege', 'ranged'],
  },
  knight: {
    id: 'knight',
    name: 'Knight',
    attack: 12,
    defense: 8,
    hp: 70,
    speed: 3,
    range: 1,
    trainCost: { food: 25, iron: 15, gold: 15 },
    trainTicks: 10,
    upkeepPerTick: { food: 2, gold: 2 },
    requires: { tech: 'steel' },
    tags: ['cavalry', 'melee'],
  },
  musketeer: {
    id: 'musketeer',
    name: 'Musketeer',
    attack: 14,
    defense: 5,
    hp: 45,
    speed: 2,
    range: 4,
    trainCost: { food: 20, iron: 15, gold: 10 },
    trainTicks: 8,
    upkeepPerTick: { food: 1, gold: 1.5 },
    requires: { tech: 'gunpowder' },
    tags: ['ranged'],
  },
  elite_guard: {
    id: 'elite_guard',
    name: 'Elite Guard',
    attack: 16,
    defense: 12,
    hp: 80,
    speed: 2,
    range: 1,
    trainCost: { food: 30, iron: 20, gold: 25 },
    trainTicks: 15,
    upkeepPerTick: { food: 2, gold: 3 },
    requires: { tech: 'military_mastery' },
    tags: ['melee', 'elite'],
  },
};

export const UNIT_LIST = Object.values(UNIT_DEFS);
